# Generated by Django 5.0.8 on 2024-09-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblogpost',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
