# Generated by Django 5.1.1 on 2025-05-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagement', '0006_userblogcomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblogcomment',
            name='parent',
        ),
    ]
