# Generated by Django 5.0.8 on 2024-09-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
