# Generated by Django 5.1.1 on 2025-03-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
